[package]
name = "docker-display"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.23.0", features = ["full"] }
hyper = "0.14"
hyperlocal = "0.8"
serde = "1.0.157"
serde_json = "1.0.94"
futures = "0.3.27"
termion = "2.0.1"
colored = "2.0.0"
